language: python
before_script:
 - echo 'US/Pacific' | sudo tee /etc/timezone
 - sudo dpkg-reconfigure --frontend noninteractive tzdata
python:
  - "2.7"
install: "pip install -r requirements.txt"
script: bash -xe pylint-everything.sh
